version: '3'
services:

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - ./apps/metabiz/source/:/var/www/metabiz
    - ./apps/kowalski/source/:/var/www/kowalski
#    - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./docker/nginx/sites/:/etc/nginx/conf.d/
    - ./docker/nginx/ssl/:/etc/ssl/
    networks:
    - app-network

  metabiz:
    build:
      context: apps/metabiz
      dockerfile: Dockerfile
    image: digitalocean.com/php
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: metabiz
      SERVICE_TAGS: dev
    working_dir: /var/www/metabiz
    volumes:
    - ./apps/metabiz/source/:/var/www/metabiz
    - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
    - app-network

  kowalski:
    build:
      context: apps/kowalski
      dockerfile: Dockerfile
    image: digitalocean.com/php
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: kowalski
      SERVICE_TAGS: dev
    working_dir: /var/www/kowalski
    volumes:
    - ./apps/kowalski/source/:/var/www/kowalski
    - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
    - app-network

  db:
    image: mysql:8.0
    restart: 'on-failure'
    tty: true
    ports:
    - "3306:3306"
    environment:
      MYSQL_DATABASE: local_db
      MYSQL_ROOT_PASSWORD: root
      SERVICE_NAME: mysql
      SERVICE_TAGS: dev
    volumes:
    - ./dbdata/db:/var/lib/mysql/
    - ./docker/mysql/my.cnf:/var/lib/mysql/my.cnf
    networks:
    - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local